### PR TITLE
Fix `splice_impl` and `tee_impl`: Fix readiness and make returned fut `Send`

### LINKED ISSUE #26: Splice between a pipe and a socket
I can see you can zero-copy-move data between the pipes.
Is there a way to move the data from a socket to a pipe and from a pipe to a socket by using splice/tee?

### PR DESCRIPTION
**Pull request by NobodyXu**
Fixed #26 

Fix:
 - `splice_impl`: Make auto-generated `Future` to be `Send`.
 - `splice_impl`: Fix readiness detection using `test_read_write_readiness`
 - `tee_impl`: Fix readiness detection using `test_read_write_readiness`
 - `test_read_write_readiness`: Implemented using `libc::poll`

Signed-off-by: Jiahao XU <Jiahao_XU@outlook.com>

### CODE REVIEW

**Comment by pkolaczk** [comment]
Wow! That was fast!

**Comment by pkolaczk** [comment]
Not it compiles fine for me!

File: src/lib.rs [hunk 1]
```diff
@@ -264,23 +267,24 @@ async fn splice_impl(
...
-
     loop {
-        let ret = unsafe { libc::splice(fd_in, off_in, fd_out, off_out, len, flags) };
+        let ret =
+            unsafe { libc::splice(fd_in, as_ptr(off_in), fd_out, as_ptr(off_out), len, flags) };
         match cvt!(ret) {
-            Err(e) if is_wouldblock(&e) => (),
+            Err(e) if is_wouldblock(&e) => {
+                read_ready.clear_ready();
+                write_ready.clear_ready();
```
Comment (pkolaczk) [inline src/lib.rs:283]: How do we know which end blocked?

Comment (NobodyXu) [reply src/lib.rs:283]: Honestly, I don't know the correct way here.

I don't know for sure whether it is reader that is going to block or writer.

Maybe I should just launch a `libc::read` and `libc::write` to test it out.

At this rate, I might need to completely rewrite the `splice` and `tee` API in another PR.

Comment (pkolaczk) [reply src/lib.rs:283]: Aargh, the libc splice API doesn't tell which one blocked :(
But maybe that's actually fine... Tokio will poll this future again once any readiness notification comes from any of those two. So that's probably correct.

Comment (NobodyXu) [reply src/lib.rs:292]: Aha, sorry I was distracted right now, I will come back to this later.

Comment (NobodyXu) [reply src/lib.rs:292]: > But maybe that's actually fine... Tokio will poll this future again once any readiness notification comes from any of those two. So that's probably correct. But then you probably don't want to wait on readable / writable in 213, 214, but just go straight to the splice call.

Hmmm...

Let me have a try.

Comment (NobodyXu) [reply src/lib.rs:292]: After a second thought, I think just polling reader or writer is not robust, so I decide to go with the original idea of manually `read` and `write` to test whether they are ready.

Comment (NobodyXu) [reply src/lib.rs]: @pkolaczk Done!

Can you please try this again?

Comment (pkolaczk) [reply src/lib.rs]: Data gets through this time, but it spins on a core again after the first message.

Comment (pkolaczk) [reply src/lib.rs]: The read end is stuck marked readable after reading the first message, even though there is not more data available.

Comment (pkolaczk) [reply src/lib.rs]: No, it is not because of that select.
First, that select was there before my attempt to switch to zero copy and it worked flawlessly.
Second, if you look carefully, the code doing splicing is enclosed in a loop, so that select has totally nothing to do with it - the future in the select does not complete until the stream is closed.

Comment (pkolaczk) [reply src/lib.rs]: Anyway, I removed the select totally (assuming I'm testing only one half of the connection now), and the problem remains.

Comment (NobodyXu) [reply src/lib.rs]:
```
        src.readable().await?;                        // this passes immediately on the second loop cycle, even though there are no data
```

This is because `splice_impl` does not clear the ready flag on success.
But this should not become a problem, since `test_read_ready` should handle that situation.

Possible reasons for infinite loop is that `splice_impl` and `tee_impl` does not handle the case where Eof happens and `splice`/`tee` returns 0.

Comment (pkolaczk) [reply src/lib.rs]: Wait, but I didn't even get to the EOR. The stream is still open when the spin happens.

Comment (NobodyXu) [reply src/lib.rs]: Can you use the debugger or `strace` to find out which line the code is blocked on?

Comment (pkolaczk) [reply src/lib.rs]: Spinning on splice / read / write:
```
[pid 50938] read(7, "", 0)              = 0
[pid 50938] write(12, "", 0)            = 0
[pid 50938] splice(7, NULL, 12, NULL, 4096, SPLICE_F_NONBLOCK) = -1 EAGAIN (Zasoby chwilowo niedostępne)
[pid 50938] read(7, "", 0)              = 0
[pid 50938] write(12, "", 0)            = 0
[pid 50938] splice(7, NULL, 12, NULL, 4096, SPLICE_F_NONBLOCK) = -1 EAGAIN (Zasoby chwilowo niedostępne)
[pid 50938] read(7, "", 0)              = 0
[pid 50938] write(12, "", 0)            = 0
[pid 50938] splice(7, NULL, 12, NULL, 4096, SPLICE_F_NONBLOCK) = -1 EAGAIN (Zasoby chwilowo niedostępne)
[pid 50938] read(7, "", 0)              = 0
[pid 50938] write(12, "", 0)            = 0
[pid 50938] splice(7, NULL, 12, NULL, 4096, SPLICE_F_NONBLOCK) = -1 EAGAIN (Zasoby chwilowo niedostępne)
[pid 50938] read(7, "", 0)              = 0
[pid 50938] write(12, "", 0)            = 0
[pid 50938] splice(7, NULL, 12, NULL, 4096, SPLICE_F_NONBLOCK) = -1 EAGAIN (Zasoby chwilowo niedostępne)
[pid 50938] read(7, "", 0)              = 0
[pid 50938] write(12, "", 0)            = 0
[pid 50938] splice(7, NULL, 12, NULL, 4096, SPLICE_F_NONBLOCK) = -1 EAGAIN (Zasoby chwilowo niedostępne)
[pid 50938] read(7, "", 0)              = 0
[pid 50938] write(12, "", 0)            = 0
[pid 50938] splice(7, NULL, 12, NULL, 4096, SPLICE_F_NONBLOCK) = -1 EAGAIN (Zasoby chwilowo niedostępne)
[pid 50938] read(7, "", 0)              = 0
[pid 50938] write(12, "", 0)            = 0
[pid 50938] splice(7, NULL, 12, NULL, 4096, SPLICE_F_NONBLOCK) = -1 EAGAIN (Zasoby chwilowo niedostępne)
[pid 50938] read(7, "", 0)              = 0
[pid 50938] write(12, "", 0)            = 0
[pid 50938] splice(7, NULL, 12, NULL, 4096, SPLICE_F_NONBLOCK) = -1 EAGAIN (Zasoby chwilowo niedostępne)
```

Comment (pkolaczk) [reply src/lib.rs]: And logically we're blocked in the `splice_from` future. So tokio is polling that future all the time as fast as it can.

Comment (pkolaczk) [reply src/lib.rs]: Yeah, read/write return 0, success, so it doesn't clear the readable/writable readiness.

Comment (NobodyXu) [reply src/lib.rs]: I will switch to `select` then...
It's efficient enough for polling two fds.

Comment (pkolaczk) [reply src/lib.rs]: I just wonder, what happens if we clear readiness of both? We cannot be reading / writing to those FDs anyway, when we are logically still running that future. So maybe we are overthinking it.

Comment (NobodyXu) [reply src/lib.rs]: I remembered that `tokio` uses `epoll` with the edge-triggered mode, meaning once `epoll` considers a fd as ready, it won't return readiness for it again until the syscalls performed on it returns `EAGAIN`.

Comment (NobodyXu) [reply src/lib.rs]: There's a detailed description of edge-triggered vs level-triggered in the [man page](https://man7.org/linux/man-pages/man7/epoll.7.html).

Comment (pkolaczk) [reply src/lib.rs]: I mean - If we clear both of them upon receiving EAGAIN, one of them will trigger the epoll event and will make tokio poll us again. Then we call splice and if it succeeds, we set readable / writable status on both again.

Comment (NobodyXu) [reply src/lib.rs]: > one of them will trigger the epoll event and will make tokio poll us again

Yeah, but then we would block forever when `epoll`ing the other one, who doesn't return `EAGAIN`.

Comment (pkolaczk) [reply src/lib.rs]: But who/what would block on epolling the other one?

Comment (NobodyXu) [reply src/lib.rs]: I've pushed another commit that attempts to fix this using `poll`.

`select`'s API is too hard to use, so I decided to use `poll` instead.

Comment (NobodyXu) [reply src/lib.rs]: > one of them will trigger the epoll event and will make tokio poll us again.

You misunderstood how it works.

`epoll` treats each fd separately.
So I/O on one fd returns `EAGAIN` under edge-triggered mode makes `epoll` poll for that particular fd again, but the other fd does not get polled.

Comment (pkolaczk) [reply src/lib.rs]: Ok. Now it works, the communicatin goes both ways and it doesn't spin. However, I notice there is a visible, quite large latency. Responses from an echo server through this proxy come after 1 second on loopback.

Comment (pkolaczk) [reply src/lib.rs]: Ah, got it. Setting has_more_data to `false` reduced the delay.

Comment (NobodyXu) [reply src/lib.rs]: > has_more_data to `false`

Oops, I didn't know that.
I guess the kernel was doing some preparation for more data, like allocation?

How much of the latency do you get after disable `has_more_data`?

Comment (NobodyXu) [reply src/lib.rs]: Out of curiosity, how much of the throughput do you get and how does it compare to simple read + write?

Comment (pkolaczk) [reply src/lib.rs]: I don't have a good framework for measuring that accurately (yet), but it is a night-and-day difference. 
Like, with `has_more_data = true` it felt as if I was talking to a machine on the other side of the planet. 
After setting to false, responses are immediate, I can't sense I'm interacting through a proxy.

I guess it just waits for more data to come, before pushing out a packet to the remote end.

Comment (NobodyXu) [reply src/lib.rs]: > I guess it just waits for more data to come, before pushing out a packet to the remote end.

Emmm, that's completely unexpected...

Comment (pkolaczk) [reply src/lib.rs]: > Out of curiosity, how much of the throughput do you get and how does it compare to simple read + write?

I managed to measure it once, and got 1.4 GB/s when pushing data from `/dev/zero` -> `nc`  -> my proxy -> `nc` -> /dev/null.
But with traditional copying I'm getting 1.3 GB/s so honestly it is a bit disappointing. 

Tried to measure it more than once, but it is constantly locking up. Something is still not ok.

**Comment by NobodyXu** [comment]
> After testing it a bit more with `dd` piped to `nc`, I noticed it sometimes locks up.

I think you can use `strace` again to see which syscall is blocking it, or you can share the relevant code, otherwise I can't help you find the problem.

File: src/lib.rs [hunk 2]
```diff
@@ -206,17 +256,43 @@ impl<'a, 'b> AtomicWriteIoSlices<'a, 'b> {
...
+                };
+
+                if !read_readiness {
+                    read_ready.clear_ready();
+                    read_ready = pipe_in.0.readable().await?;
+                }
+
+                if !write_readiness {
+                    write_ready.clear_ready();
+                    write_ready = pipe_out.0.readable().await?;
```
[the remark this answers is not in the document]
Comment (NobodyXu) [reply src/lib.rs:293]: Oh you are right!

thanks for pointing out, will push a new commit soon.

[the remark this answers is not in the document]
Comment (NobodyXu) [reply src/lib.rs]: Thanks for catching the error!

It is now fixed.

**Comment by pkolaczk** [comment]
It doesn't lock up after the fix.

**Comment by NobodyXu** [comment]
@pkolaczk Is there any other regressions/bugs you encountered or any performance-wise problem?

**Comment by pkolaczk** [comment]
At the moment it looks like it works, but I haven't tested it very extensively. 

One thing that blocks me from testing it better is the fact that this crate forces me to use a different representation of my streams, instead of just the `OwnedReadHalf` and `OwnedWriteHalf`. Which makes it hard to integrate with the rest of the code, where I have more tests and benchmarks. It cannot just swap a zero-copy implementation into the existing code base. Type aliases solve it only to some degree, as there is some other code now that relies on my stream representation to offer stuff that is not available on AsyncFd (e.g. fetching the peer addresses). I could probably get away from this by wrapping + some additional traits, but this adds a lot of accidental complexity and honestly I'd want to avoid it.  

Having said that, this PR is already a huge improvement over what was before, so I'm for merging it and maybe let's address the API thing and eventual perf improvements in a separate PR?

**Comment by NobodyXu** [comment]
@yskszk63 Can you review this PR please?

**Comment by yskszk63** [comment]
@NobodyXu @pkolaczk 
Sorry for the late response.
Thanks for the great work!

**Comment by yskszk63** [comment]
It has been released as v0.2.12.
